### ISSUE TITLE
Love it! I suggest to tag releases

### ISSUE THREAD

**Issue by DannyBen** [fschuindt/toucan#1]
This looks like a really cool concept, and I would love to get my hands on it.

I have a small suggestion - perhaps git-tag the releases with the same version number (`v0.0.1`) so that we see them in the [releases tab][1]?

[1]: https://github.com/fschuindt/toucan/releases

**Comment by fschuindt** [comment]
Thank you!

I have stated the following at the README file:
>Any 0.0.X version is experimental. Things can be changed without changing the version tag itself.

The project lacks testing, documentation and other stuff I think it's important to have like CI and etc. So I'm trying to avoid a proper release until it. What do you think?

If you think it's really a need I can do it for sure. :)

**Comment by DannyBen** [comment]
I totally get it, I am also adapting the same principle of 0.0.x being "not ready for public consumption".
Nonetheless, I think that even these versions are worth at least a tag ([example in one of my gems][1])- this way GitHub automatically marks it in the Releases tab, and then people can see when a new version comes out and play with it. In addition, 

But of course, its a minor suggestion coming from a selfish place of wanting to know when a new release is out directly from GitHub... :)

Anyways - I can't wait to play with it, seems to be very useful.

[1]: https://github.com/DannyBen/madness/releases?after=v0.0.6

**Comment by fschuindt** [comment]
Great! I have opened the issue #3, which plans to solve it. I will try to do it soon. So it's just a issue to later become a PR.

I'm closing it here so we avoid duplicates. Thank you!
